### PR TITLE
Don't send empty email

### PR DESCRIPTION
**Pull request by szepeviktor**
`$messages_buffer` it not used???

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you!
Could it be that you will complete Tripwire in the near future?

**Comment by szepeviktor** [comment]
- phpmailer
- $messages_buffer
- etc.

**Comment by lasergoat** [comment]
it could be! I haven't had time to work on it or need it. I am using an old version (before I forked from Lucanos) of it on a production server. how are you using it?

**Comment by szepeviktor** [comment]
It is only needed on shared hosting. A server has better tools.
I've just started using your fork with some adjustments.
https://github.com/szepeviktor/Tripwire/commit/d6148749dff530adc3bce48956cfaf62f939c6db

**Comment by szepeviktor** [comment]
This code looks much better than the original.

**Comment by lasergoat** [comment]
very cool. is yours in a working state?

**Comment by szepeviktor** [comment]
Yes.
But I do need directory exclusion.
Are planning to work on Tripwire?

**Comment by szepeviktor** [comment]
Here they are: https://github.com/szepeviktor/Tripwire/commits/master

**Pull request merged**
